// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "AppResources.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class AppResources
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator
// App/Edition: CDN / CloudFlare/
// User:        2sic Web-Developer
namespace AppCode.Data
{
  // This is a generated class for AppResources (scope: System.App)
  // To extend/modify it, see instructions above.

  /// <summary>
  /// AppResources data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.FlushAll`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  /// <remarks>
  /// This Content-Type is NOT in the default scope, so you may not see it in the Admin UI. It's in the scope System.App.
  /// </remarks>
  public partial class AppResources: AutoGenerated.ZAutoGenAppResources
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for System.App.AppResources in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenAppResources: Custom.Data.CustomItem
  {
    /// <summary>
    /// FlushAll as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("FlushAll", scrubHtml: true) etc.
    /// </summary>
    public string FlushAll => _item.String("FlushAll", fallback: "");

    /// <summary>
    /// FlushUrl as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("FlushUrl", scrubHtml: true) etc.
    /// </summary>
    public string FlushUrl => _item.String("FlushUrl", fallback: "");
  }
}